// Generated by CoffeeScript 1.3.3

/*
  This is the main script file. It can attach to the terminal
*/


/*
  Register the things
*/


(function() {
  var leaveFullSizeMode, next, previous, question, questions, results;

  this.webterm = $('#terminal').terminal(interpreter, basesettings);

  $('#buttonNext').click(function() {
    return next();
  });

  $('#buttonPrevious').click(function() {
    return previous();
  });

  /*
    Start with the questions
  */


  questions = [];

  question = 0;

  next = function() {
    question++;
    questions[question]();
    return results.clear();
  };

  previous = function() {
    question--;
    questions[question]();
    return results.clear();
  };

  results = {
    set: function(htmlText) {
      return $('#results').html(htmlText);
    },
    clear: function() {
      return $('#results').html("");
    }
  };

  questions.push(function() {
    $('#instructions').html("<h1>one</h1>\nWelcome\n\nPlease type docker search ubuntu\n");
    return window.immediateCallback = function(input) {
      console.log(input);
      if (Object.equal(input, ['docker', 'search', 'ubuntu'])) {
        results.set("yeey! hurray, woohooo, you did it, amazing, you are awesome, you completed the first assignment.");
      } else {
        results.set("That was not the right command.");
      }
    };
  });

  questions.push(function() {
    $('#instructions').html("<h1>two</h1>\n<p>Great. Now you know how to find images, lets download them. The command to use is \"pull\".</p>\n<p>Go ahead and pull the tutorial image</p>");
    return window.finishedCallback = function(input) {
      console.log(input);
      if (Object.equal(input, ['docker', 'pull', 'ubuntu'])) {
        $('#results').html("yeey! hurray, woohooo, you did it, amazing, you are awesome, you completed the second assignment.");
      }
    };
  });

  questions[0]();

  /*
    Make the resizing possible
  */


  $('#fullSizeOpen').click(function() {
    console.debug("going to fullsize mode");
    $('#overlay').addClass('fullsize');
    $('#main').addClass('fullsize');
    return $('#tutorialTop').addClass('fullsize');
  });

  $('#fullSizeClose').click(function() {
    return leaveFullSizeMode();
  });

  leaveFullSizeMode = function() {
    console.debug("leaving full-size mode");
    $('#overlay').removeClass('fullsize');
    $('#main').removeClass('fullsize');
    return $('#tutorialTop').removeClass('fullsize');
  };

}).call(this);
