pre {
    background-color: #F5F5F5;
    border: 1px solid rgba(0, 0, 0, 0.15);
    border-radius: 4px 4px 4px 4px;
    display: block;
    font-size: 13px;
    line-height: 20px;
    margin: 0 0 10px;
    padding: 9.5px;
    white-space: pre-wrap;
    word-break: break-all;
    word-wrap: break-word;
}
code, pre {
    border-radius: 3px 3px 3px 3px;
    color: #333333;
    font-family: Monaco,Menlo,Consolas,"Courier New",monospace;
    font-size: 12px;
    padding: 0 3px 2px;
}

.terminal {
	color: #AAAAAA;
	background-color: black;
}

.terminal  span.command {
	color: white;
	font-weight: bold;
}

.error_input {
    border-color: #B94A48 !important;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset !important;
}